### ISSUE TITLE
Build problems with EDSDK 3.4

### ISSUE THREAD

**Issue by mruegenberg** [hezhao/Calibrator#2]
Hi,
I get the following errors when trying to build with EDSK 3.4:

```
/usr/local/Cellar/qt/4.8.5/include/QtCore/qmetatype.h:256:5: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]
    register int id = qMetaTypeId<T>();
    ^~~~~~~~~
6 warnings generated.
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -std=c++11 -O2 -arch x86_64 -Wall -W -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.5/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/include -I../src -IGeneratedFiles -I/usr/local/include -I../lib/EDSDK/Header -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -IGeneratedFiles -F/usr/local/Cellar/qt/4.8.5/lib -o Camera.o ../src/Camera.cpp
../src/Camera.cpp:229:16: error: no matching function for call to 'EdsGetLength'
       error = EdsGetLength(stream, &length);
               ^~~~~~~~~~~~
../lib/EDSDK/Header/EDSDK.h:926:17: note: candidate function not viable: no known conversion from 'EdsUInt32 *' (aka 'unsigned int *') to 'EdsUInt64 *' (aka 'unsigned long long *') for 2nd argument
EdsError EDSAPI EdsGetLength(
                ^
../src/Camera.cpp:324:9: error: no matching function for call to 'EdsGetLength'
        EdsGetLength( stream, &length );
        ^~~~~~~~~~~~
../lib/EDSDK/Header/EDSDK.h:926:17: note: candidate function not viable: no known conversion from 'EdsUInt32 *' (aka 'unsigned int *') to 'EdsUInt64 *' (aka 'unsigned long long *') for 2nd argument
EdsError EDSAPI EdsGetLength(
                ^
../src/Camera.cpp:382:64: warning: unused parameter 'inEvent' [-Wunused-parameter]
    EdsError EDSCALLBACK Camera::handlePropertyEvent(EdsUInt32 inEvent, EdsUInt32 inPropertyID, EdsUInt32 inParam, EdsVoid* inContext) {
                                                               ^
../src/Camera.cpp:382:83: warning: unused parameter 'inPropertyID' [-Wunused-parameter]
    EdsError EDSCALLBACK Camera::handlePropertyEvent(EdsUInt32 inEvent, EdsUInt32 inPropertyID, EdsUInt32 inParam, EdsVoid* inContext) {
                                                                                  ^
../src/Camera.cpp:382:107: warning: unused parameter 'inParam' [-Wunused-parameter]
    EdsError EDSCALLBACK Camera::handlePropertyEvent(EdsUInt32 inEvent, EdsUInt32 inPropertyID, EdsUInt32 inParam, EdsVoid* inContext) {
                                                                                                          ^
../src/Camera.cpp:382:125: warning: unused parameter 'inContext' [-Wunused-parameter]
    EdsError EDSCALLBACK Camera::handlePropertyEvent(EdsUInt32 inEvent, EdsUInt32 inPropertyID, EdsUInt32 inParam, EdsVoid* inContext) {
                                                                                                                            ^
../src/Camera.cpp:386:80: warning: unused parameter 'inParam' [-Wunused-parameter]
    EdsError EDSCALLBACK Camera::handleStateEvent(EdsUInt32 inEvent, EdsUInt32 inParam, EdsVoid* inContext) {
                                                                               ^
5 warnings and 2 errors generated.
make: *** [Camera.o] Error 1
```

It works with version 3.2.1.

It is also unclear what you mean by "replace lib/EDSDK/Framekwork/EDSDK.framework to be the 64 bit version". There is only one framework? 

I also had to manually move EDSDK.framework/DPP.framework to `bin/Calibrator.app/Contents/Frameworks` for the program to start.

**Comment by hezhao** [comment]
If you are not using the [latest cameras](https://www.didp.canon-europa.com/) that are only available since v3.2, just download the EDSDK version listed in the readme file.

I haven't tried EDSDK version 3. Calibrator uses [EDSDK-cpp](https://github.com/hezhao/EDSDK-cpp) internally, which is derived from [Cinder-EDSDK](https://github.com/pizthewiz/Cinder-EDSDK) by stripping away Cinder code. [ofxEdsdk](https://github.com/kylemcdonald/ofxEdsdk) is also a good library, but unfortunately it still needs a lot of work to strip away openframeworks code.

I can use some help to keep the [EDSDK-cpp](https://github.com/hezhao/EDSDK-cpp) version up to date.
